# Generated by Django 4.2.7 on 2025-09-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0002_remove_studentprofile_gpa_studentprofile_cgpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship_app.signup'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship_app.signup'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scholarship_app.signup'),
        ),
    ]
