# Generated by Django 5.2.6 on 2025-09-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_app', '0003_signup_alter_forumreply_user_alter_forumtopic_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='min_gpa',
            new_name='min_cgpa',
        ),
    ]
