from django.core.management.base import BaseCommand
from scholarship_app.models import Scholarship
import json
from datetime import datetime, timedelta

class Command(BaseCommand):
    help = 'Load sample scholarship data with real Indian scholarships'

    def handle(self, *args, **options):
        scholarships = [
            # ===== GOVERNMENT & NATIONAL LEVEL SCHOLARSHIPS =====
            {
                'title': 'National Talent Search Examination (NTSE)',
                'provider': 'NCERT',
                'amount': '125000.00',
                'deadline': datetime.now() + timedelta(days=30),
                'description': 'Prestigious national-level scholarship for Class X students to identify and nurture talent.',
                'eligibility': 'Indian national, studying in Class X, minimum 60% (6.0 CGPA) in Class IX.',
                'application_process': 'Apply through State/UT liaison officers. Two-stage exam.',
                'website': 'https://ncert.nic.in/national-talent-examination.php',
                'scholarship_type': 'merit',
                'education_level': 'school',
                'min_cgpa': '6.00',
                'max_age': 18,
                'min_age': 14,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Kishore Vaigyanik Protsahan Yojana (KVPY)',
                'provider': 'Indian Institute of Science (IISc)',
                'amount': '700000.00',
                'deadline': datetime.now() + timedelta(days=45),
                'description': 'Fellowship program to encourage students to take up research careers in Science.',
                'eligibility': 'Indian national, studying in Class XI/XII or 1st year UG in Basic Sciences.',
                'application_process': 'Online application followed by aptitude test and interview.',
                'website': 'https://kvpy.iisc.ac.in/',
                'scholarship_type': 'merit',
                'education_level': 'school',
                'min_cgpa': '6.00',
                'max_age': 20,
                'min_age': 16,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Science", "Mathematics"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Central Sector Scheme of Scholarships',
                'provider': 'Ministry of Education, GoI',
                'amount': '200000.00',
                'deadline': datetime.now() + timedelta(days=60),
                'description': 'Scholarships for students who have secured above 80% in Class XII pursuing regular UG courses.',
                'eligibility': 'Family income < Rs. 8 Lakh/annum, top 20% in Class XII board exams.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '800000.00',
            },
            {
                'title': 'Prime Minister’s Scholarship Scheme for RPF/RPSF',
                'provider': 'Ministry of Railways',
                'amount': '300000.00',
                'deadline': datetime.now() + timedelta(days=70),
                'description': 'Scholarship for wards of RPF/RPSF personnel killed or disabled on duty.',
                'eligibility': 'Ward of RPF/RPSF personnel, family income < Rs. 6 Lakh/annum, min 60% in previous exam.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '600000.00',
            },
            {
                'title': 'AICTE Pragati Scholarship for Girls',
                'provider': 'AICTE',
                'amount': '500000.00',
                'deadline': datetime.now() + timedelta(days=80),
                'description': 'Scholarship for girls pursuing technical education in AICTE approved institutions.',
                'eligibility': 'Girl student, family income < Rs. 8 Lakh/annum, admission in AICTE approved college.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Engineering", "Technology", "Architecture", "Pharmacy"]',
                'minority_preferences': '["Women in STEM"]',
                'disability_preferences': '[]',
                'income_max': '800000.00',
            },
            {
                'title': 'AICTE Saksham Scholarship',
                'provider': 'AICTE',
                'amount': '500000.00',
                'deadline': datetime.now() + timedelta(days=85),
                'description': 'Scholarship for differently-abled students pursuing technical education.',
                'eligibility': 'Student with disability (>40%), family income < Rs. 8 Lakh/annum, admission in AICTE approved college.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'disability',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Engineering", "Technology", "Architecture", "Pharmacy"]',
                'minority_preferences': '[]',
                'disability_preferences': '["Physically Disabled", "Hearing Impairment", "Visual Impairment"]',
                'income_max': '800000.00',
            },
            {
                'title': 'National Fellowship for SC Students',
                'provider': 'UGC',
                'amount': '3100000.00',
                'deadline': datetime.now() + timedelta(days=90),
                'description': 'Fellowship for SC students pursuing M.Phil. and Ph.D. courses in universities/institutions.',
                'eligibility': 'SC candidate, post-graduation degree, admission to full-time M.Phil/Ph.D.',
                'application_process': 'Online application through UGC website.',
                'website': 'https://www.ugc.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'graduate',
                'min_cgpa': '6.50',
                'max_age': 40,
                'min_age': 22,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Scheduled Caste"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Maulana Azad National Fellowship',
                'provider': 'UGC',
                'amount': '3100000.00',
                'deadline': datetime.now() + timedelta(days=95),
                'description': 'Fellowship for students from minority communities pursuing M.Phil. and Ph.D.',
                'eligibility': 'Candidate from minority community (Muslim, Christian, Sikh, Buddhist, Parsi, Jain), post-graduation degree.',
                'application_process': 'Online application through UGC website.',
                'website': 'https://www.ugc.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'graduate',
                'min_cgpa': '6.50',
                'max_age': 40,
                'min_age': 22,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Minority Community"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Post Matric Scholarship for SC/ST/OBC',
                'provider': 'Ministry of Social Justice & Empowerment',
                'amount': '150000.00',
                'deadline': datetime.now() + timedelta(days=100),
                'description': 'Scholarship for SC/ST/OBC students studying at post-matriculation level.',
                'eligibility': 'SC/ST/OBC candidate, family income < specified limit, studying in post-matric class.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '5.50',
                'max_age': 30,
                'min_age': 16,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Scheduled Caste", "Scheduled Tribe", "Other Backward Classes"]',
                'disability_preferences': '[]',
                'income_max': '250000.00',
            },
            {
                'title': 'Pre Matric Scholarship for Minorities',
                'provider': 'Ministry of Minority Affairs',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=110),
                'description': 'Scholarship for minority students studying in classes I to X.',
                'eligibility': 'Minority community student, family income < Rs. 1 Lakh/annum, min 50% in previous exam.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'school',
                'min_cgpa': '5.00',
                'max_age': 16,
                'min_age': 10,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Minority Community"]',
                'disability_preferences': '[]',
                'income_max': '100000.00',
            },
            {
                'title': 'Fellowship for University Teachers for PhD',
                'provider': 'UGC',
                'amount': '1500000.00',
                'deadline': datetime.now() + timedelta(days=120),
                'description': 'Fellowship for regular teachers in universities/colleges to pursue Ph.D.',
                'eligibility': 'Regular teacher, PG degree, min 55% marks at PG level.',
                'application_process': 'Application through concerned university/college.',
                'website': 'https://www.ugc.gov.in/',
                'scholarship_type': 'merit',
                'education_level': 'graduate',
                'min_cgpa': '5.50',
                'max_age': 50,
                'min_age': 30,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Dr. Ambedkar Post Matric Scholarship for EBC',
                'provider': 'Department of Social Justice & Empowerment',
                'amount': '120000.00',
                'deadline': datetime.now() + timedelta(days=130),
                'description': 'Scholarship for Economically Backward Class (EBC) students pursuing post-matriculation studies.',
                'eligibility': 'EBC candidate, family income < Rs. 1 Lakh/annum, studying in post-matric class.',
                'application_process': 'Online application through National Scholarship Portal (NSP).',
                'website': 'https://scholarships.gov.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '5.00',
                'max_age': 30,
                'min_age': 16,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '100000.00',
            },
            {
                'title': 'Indira Gandhi Scholarship for Single Girl Child',
                'provider': 'UGC',
                'amount': '432000.00',
                'deadline': datetime.now() + timedelta(days=140),
                'description': 'Scholarship for single girl children pursuing Master’s degree courses.',
                'eligibility': 'Single girl child, age < 30 years, admitted to 1st year Master’s degree.',
                'application_process': 'Online application through UGC website.',
                'website': 'https://www.ugc.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'graduate',
                'min_cgpa': '6.00',
                'max_age': 30,
                'min_age': 20,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Women"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Rajiv Gandhi National Fellowship for SC/ST',
                'provider': 'UGC',
                'amount': '3100000.00',
                'deadline': datetime.now() + timedelta(days=150),
                'description': 'Fellowship for SC/ST students pursuing M.Phil. and Ph.D. courses.',
                'eligibility': 'SC/ST candidate, post-graduation degree, admission to full-time M.Phil/Ph.D.',
                'application_process': 'Online application through UGC website.',
                'website': 'https://www.ugc.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'graduate',
                'min_cgpa': '6.00',
                'max_age': 40,
                'min_age': 22,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Scheduled Caste", "Scheduled Tribe"]',
                'disability_preferences': '[]',
            },

            # ===== PRIVATE & CORPORATE SCHOLARSHIPS =====
            {
                'title': 'Aditya Birla Group Scholarship',
                'provider': 'Aditya Birla Group',
                'amount': '540000.00',
                'deadline': datetime.now() + timedelta(days=15),
                'description': 'Merit-based scholarship for brilliant students with limited financial means.',
                'eligibility': 'Family income < Rs. 4 Lakh/annum, top 1% in Class XII board exams.',
                'application_process': 'Application through nominated colleges/universities. Includes essays and interviews.',
                'website': 'https://www.adityabirla.com/sustainability/community/scholarships',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '9.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '400000.00',
            },
            {
                'title': 'Narotam Sekhsaria Scholarship Programme',
                'provider': 'Narotam Sekhsaria Foundation',
                'amount': '2000000.00',
                'deadline': datetime.now() + timedelta(days=50),
                'description': 'Scholarship for Indian students with outstanding academic record to pursue PG studies in India or abroad.',
                'eligibility': 'Indian national under 30 years, first-class degree, confirmed admission offer.',
                'application_process': 'Online application, statement of purpose, proof of admission, interviews.',
                'website': 'https://www.nsscholarship.net/',
                'scholarship_type': 'merit',
                'education_level': 'graduate',
                'min_cgpa': '7.50',
                'max_age': 30,
                'min_age': 22,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'JN Tata Endowment Scholarship',
                'provider': 'JN Tata Endowment',
                'amount': '1500000.00',
                'deadline': datetime.now() + timedelta(days=65),
                'description': 'Loan scholarship for Indian nationals for higher studies abroad in all disciplines.',
                'eligibility': 'Indian national, first-class degree, secured admission for PG abroad.',
                'application_process': 'Online application, statement of purpose, academic documents, interview.',
                'website': 'https://www.dorabjitatatrust.org/',
                'scholarship_type': 'merit',
                'education_level': 'graduate',
                'min_cgpa': '7.50',
                'max_age': 45,
                'min_age': 22,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'L’Oréal India For Young Women in Science Scholarship',
                'provider': 'L’Oréal India',
                'amount': '250000.00',
                'deadline': datetime.now() + timedelta(days=75),
                'description': 'Scholarship for young women pursuing graduation in Science streams.',
                'eligibility': 'Female student, Class XII Science stream with min 85%, family income < Rs. 4 Lakh/annum.',
                'application_process': 'Online application, academic documents, statement of purpose.',
                'website': 'https://www.loreal.com/en/india/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 19,
                'min_age': 16,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Science"]',
                'minority_preferences': '["Women in STEM"]',
                'disability_preferences': '[]',
                'income_max': '400000.00',
            },
            {
                'title': 'S.N. Bose Scholars Program',
                'provider': 'IUSSTF',
                'amount': '3500000.00',
                'deadline': datetime.now() + timedelta(days=160),
                'description': 'Scholarship for Indian students to pursue research internships in US universities in STEM fields.',
                'eligibility': 'Indian citizen, B.Tech/M.Sc in STEM fields, min 8.5 CGPA.',
                'application_process': 'Online application, research proposal, letters of recommendation.',
                'website': 'https://www.iusstf.org/',
                'scholarship_type': 'merit',
                'education_level': 'graduate',
                'min_cgpa': '8.50',
                'max_age': 28,
                'min_age': 21,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Science", "Technology", "Engineering", "Mathematics"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'K.C. Mahindra Scholarships for Post-Graduate Studies Abroad',
                'provider': 'K.C. Mahindra Education Trust',
                'amount': '800000.00',
                'deadline': datetime.now() + timedelta(days=170),
                'description': 'Interest-free loan scholarship for Indian students to pursue PG studies abroad.',
                'eligibility': 'Indian citizen, age < 30 years, first-class degree, secured admission abroad.',
                'application_process': 'Online application, academic documents, statement of purpose, interview.',
                'website': 'https://www.kcmtrust.org/',
                'scholarship_type': 'merit',
                'education_level': 'graduate',
                'min_cgpa': '7.50',
                'max_age': 30,
                'min_age': 22,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'HDFC Educational Crisis Scholarship',
                'provider': 'HDFC Bank',
                'amount': '75000.00',
                'deadline': datetime.now() + timedelta(days=180),
                'description': 'Scholarship support for students who have lost parents to COVID-19.',
                'eligibility': 'Student who lost parent/guardian to COVID-19, studying in Class 1 to PG.',
                'application_process': 'Online application with required documents.',
                'website': 'https://www.hdfcbank.com/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '5.00',
                'max_age': 25,
                'min_age': 6,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'IBM STEM for Girls Scholarship',
                'provider': 'IBM India',
                'amount': '50000.00',
                'deadline': datetime.now() + timedelta(days=190),
                'description': 'Scholarship for girl students from government schools to pursue STEM education.',
                'eligibility': 'Girl student from government school, studying in Class IX-XII, interest in STEM.',
                'application_process': 'Nomination by school/application through program portal.',
                'website': 'https://www.ibm.com/ibm/',
                'scholarship_type': 'minority',
                'education_level': 'school',
                'min_cgpa': '6.00',
                'max_age': 18,
                'min_age': 14,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Science", "Mathematics"]',
                'minority_preferences': '["Women in STEM"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Tata Capital Pankh Scholarship',
                'provider': 'Tata Capital',
                'amount': '60000.00',
                'deadline': datetime.now() + timedelta(days=200),
                'description': 'Scholarship for meritorious and deserving girl students pursuing professional courses.',
                'eligibility': 'Girl student, family income < Rs. 6 Lakh/annum, min 60% in previous exam.',
                'application_process': 'Online application with income and academic documents.',
                'website': 'https://www.tatacapital.com/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Women"]',
                'disability_preferences': '[]',
                'income_max': '600000.00',
            },
            {
                'title': 'Reliance Foundation Undergraduate Scholarship',
                'provider': 'Reliance Foundation',
                'amount': '400000.00',
                'deadline': datetime.now() + timedelta(days=210),
                'description': 'Scholarship for meritorious students pursuing undergraduate studies.',
                'eligibility': 'Indian citizen, min 85% in Class XII, family income < Rs. 15 Lakh/annum.',
                'application_process': 'Online application, academic documents, statement of purpose.',
                'website': 'https://www.ril.com/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '1500000.00',
            },
            {
                'title': 'DLF Foundation Scholarship',
                'provider': 'DLF Foundation',
                'amount': '36000.00',
                'deadline': datetime.now() + timedelta(days=220),
                'description': 'Scholarship for students from economically weaker sections for school and college education.',
                'eligibility': 'Family income < Rs. 3 Lakh/annum, min 60% in previous exam.',
                'application_process': 'Online application with income and academic documents.',
                'website': 'https://www.dlffoundation.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 14,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '300000.00',
            },
            {
                'title': 'LIC Golden Jubilee Scholarship',
                'provider': 'LIC India',
                'amount': '20000.00',
                'deadline': datetime.now() + timedelta(days=230),
                'description': 'Scholarship for students from economically weaker families for professional courses.',
                'eligibility': 'Family income < Rs. 2 Lakh/annum, min 60% in Class XII.',
                'application_process': 'Online application through LIC portal.',
                'website': 'https://www.licindia.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '200000.00',
            },
            {
                'title': 'Nurturing Brilliance Scholarship by Kotak Education Foundation',
                'provider': 'Kotak Education Foundation',
                'amount': '50000.00',
                'deadline': datetime.now() + timedelta(days=240),
                'description': 'Scholarship for meritorious students from underprivileged backgrounds.',
                'eligibility': 'Family income < Rs. 3 Lakh/annum, min 75% in previous exam.',
                'application_process': 'Online application with required documents.',
                'website': 'https://www.kotakeducation.org/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '7.50',
                'max_age': 22,
                'min_age': 16,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '300000.00',
            },
            {
                'title': 'Sitaram Jindal Foundation Scholarship',
                'provider': 'Sitaram Jindal Foundation',
                'amount': '12000.00',
                'deadline': datetime.now() + timedelta(days=250),
                'description': 'Scholarship for students from economically weaker sections for various courses.',
                'eligibility': 'Family income < Rs. 2 Lakh/annum, min 60% in previous exam.',
                'application_process': 'Offline application by post with documents.',
                'website': 'https://www.sjfoundation.co.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 16,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '200000.00',
            },
                        {
                'title': 'Yes Foundation Scholarship',
                'provider': 'Yes Bank',
                'amount': '50000.00',
                'deadline': datetime.now() + timedelta(days=250),
                'description': 'Scholarship for students pursuing graduation in Mass Media and related fields.',
                'eligibility': 'Indian citizen, min 65% in Class XII, pursuing Mass Media/Journalism.',
                'application_process': 'Online application through Yes Foundation website.',
                'website': 'https://www.yesfoundation.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '6.50',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Mass Media", "Journalism", "Communications"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'INSPIRE Scholarship for Higher Education (SHE)',
                'provider': 'Department of Science & Technology',
                'amount': '120000.00',
                'deadline': datetime.now() + timedelta(days=260),
                'description': 'Scholarship for top rankers in Class XII to pursue Bachelor’s and Integrated Masters in Natural Sciences.',
                'eligibility': 'Top 1% in Class XII board exams, admitted to B.Sc./M.Sc. in Natural Sciences.',
                'application_process': 'Nomination by school/application through DST portal.',
                'website': 'https://www.online-inspire.gov.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '9.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Physics", "Chemistry", "Biology", "Mathematics"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Sarla Devi Scholarship',
                'provider': 'Sarla Devi Foundation',
                'amount': '30000.00',
                'deadline': datetime.now() + timedelta(days=270),
                'description': 'Scholarship for girl students from West Bengal pursuing higher education.',
                'eligibility': 'Female student, domicile of West Bengal, min 75% in previous exam.',
                'application_process': 'Online application with academic and domicile documents.',
                'website': 'https://sarladevifoundation.org/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '7.50',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Women"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Bihar Student Credit Card Scheme',
                'provider': 'Government of Bihar',
                'amount': '4000000.00',
                'deadline': datetime.now() + timedelta(days=280),
                'description': 'Education loan scheme for students from Bihar for higher studies.',
                'eligibility': 'Domicile of Bihar, admission in recognized institution, family income < Rs. 5 Lakh/annum.',
                'application_process': 'Online application through Bihar government portal.',
                'website': 'https://www.7nishchay-yuvaupmission.bihar.gov.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '5.50',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '500000.00',
            },
            {
                'title': 'Karnataka Minority Scholarship',
                'provider': 'Karnataka Minorities Development Corporation',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=290),
                'description': 'Scholarship for minority students from Karnataka for professional courses.',
                'eligibility': 'Domicile of Karnataka, minority community, min 50% in previous exam.',
                'application_process': 'Online application through KMDC portal.',
                'website': 'https://kmdc.karnataka.gov.in/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '5.00',
                'max_age': 30,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Minority Community"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Mumbai University Scholarship for SC/ST',
                'provider': 'University of Mumbai',
                'amount': '50000.00',
                'deadline': datetime.now() + timedelta(days=300),
                'description': 'Scholarship for SC/ST students enrolled in Mumbai University.',
                'eligibility': 'SC/ST candidate, enrolled in Mumbai University, min 45% in previous exam.',
                'application_process': 'Application through college/university scholarship cell.',
                'website': 'https://mu.ac.in/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '4.50',
                'max_age': 30,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Scheduled Caste", "Scheduled Tribe"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'IIT Bombay Scholarship for SC/ST',
                'provider': 'IIT Bombay',
                'amount': '150000.00',
                'deadline': datetime.now() + timedelta(days=310),
                'description': 'Merit-cum-means scholarship for SC/ST students at IIT Bombay.',
                'eligibility': 'SC/ST candidate, enrolled in IIT Bombay, family income < specified limit.',
                'application_process': 'Application through institute’s SC/ST cell.',
                'website': 'https://www.iitb.ac.in/',
                'scholarship_type': 'minority',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Scheduled Caste", "Scheduled Tribe"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'IIM Ahmedabad Need-Based Scholarship',
                'provider': 'IIM Ahmedabad',
                'amount': '1000000.00',
                'deadline': datetime.now() + timedelta(days=320),
                'description': 'Financial aid for students with genuine financial need at IIM Ahmedabad.',
                'eligibility': 'Enrolled in IIM Ahmedabad, demonstrated financial need.',
                'application_process': 'Application through institute’s financial aid office.',
                'website': 'https://www.iima.ac.in/',
                'scholarship_type': 'need',
                'education_level': 'graduate',
                'min_cgpa': '6.00',
                'max_age': 35,
                'min_age': 21,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'AIIMS Scholarship for MBBS Students',
                'provider': 'AIIMS Delhi',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=330),
                'description': 'Scholarship for meritorious and needy MBBS students at AIIMS.',
                'eligibility': 'Enrolled in MBBS at AIIMS, min 60% in previous year, financial need.',
                'application_process': 'Application through institute’s scholarship cell.',
                'website': 'https://www.aiims.edu/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '6.00',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Medicine"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'NIT Trichy Scholarship for Toppers',
                'provider': 'NIT Trichy',
                'amount': '50000.00',
                'deadline': datetime.now() + timedelta(days=340),
                'description': 'Merit scholarship for top rankers in each branch at NIT Trichy.',
                'eligibility': 'Enrolled in NIT Trichy, top rank in branch in previous semester.',
                'application_process': 'Automatic consideration based on academic performance.',
                'website': 'https://www.nitt.edu/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'BITS Pilani Merit Scholarship',
                'provider': 'BITS Pilani',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=350),
                'description': 'Scholarship for meritorious students based on performance in previous semester.',
                'eligibility': 'Enrolled in BITS Pilani, min 8.5 CGPA in previous semester.',
                'application_process': 'Automatic consideration based on academic performance.',
                'website': 'https://www.bits-pilani.ac.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'VIT Chancellor’s Scholarship',
                'provider': 'VIT University',
                'amount': '75000.00',
                'deadline': datetime.now() + timedelta(days=360),
                'description': 'Scholarship for top rankers in VITEEE entrance exam.',
                'eligibility': 'Top rank in VITEEE, admitted to VIT University.',
                'application_process': 'Automatic award based on VITEEE rank.',
                'website': 'https://vit.ac.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '9.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'SRM University Merit Scholarship',
                'provider': 'SRM University',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=370),
                'description': 'Scholarship based on performance in SRMJEEE entrance exam.',
                'eligibility': 'High rank in SRMJEEE, admitted to SRM University.',
                'application_process': 'Automatic award based on entrance exam rank.',
                'website': 'https://www.srmist.edu.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Manipal University Scholarship',
                'provider': 'Manipal Academy of Higher Education',
                'amount': '200000.00',
                'deadline': datetime.now() + timedelta(days=380),
                'description': 'Merit scholarship for students based on entrance exam rank and academic performance.',
                'eligibility': 'High rank in MET, admitted to Manipal University.',
                'application_process': 'Automatic award based on entrance exam rank.',
                'website': 'https://manipal.edu/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Amity University Scholarship',
                'provider': 'Amity University',
                'amount': '150000.00',
                'deadline': datetime.now() + timedelta(days=390),
                'description': 'Merit scholarship for students with outstanding academic record.',
                'eligibility': 'Min 90% in Class XII, admitted to Amity University.',
                'application_process': 'Application through university scholarship portal.',
                'website': 'https://www.amity.edu/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '9.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'LPU Scholarship',
                'provider': 'Lovely Professional University',
                'amount': '200000.00',
                'deadline': datetime.now() + timedelta(days=400),
                'description': 'Scholarship based on performance in LPUNEST or Class XII marks.',
                'eligibility': 'High score in LPUNEST or min 90% in Class XII.',
                'application_process': 'Automatic award based on eligibility criteria.',
                'website': 'https://www.lpu.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '9.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Christ University Scholarship',
                'provider': 'Christ University',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=410),
                'description': 'Merit-cum-means scholarship for students at Christ University.',
                'eligibility': 'Min 85% in Class XII, family income < Rs. 5 Lakh/annum.',
                'application_process': 'Application through university scholarship cell.',
                'website': 'https://christuniversity.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '500000.00',
            },
            {
                'title': 'Symbiosis Scholarship',
                'provider': 'Symbiosis International University',
                'amount': '150000.00',
                'deadline': datetime.now() + timedelta(days=420),
                'description': 'Scholarship for meritorious and needy students at Symbiosis.',
                'eligibility': 'Min 80% in previous exam, family income < Rs. 6 Lakh/annum.',
                'application_process': 'Application through institute’s scholarship cell.',
                'website': 'https://www.siu.edu.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '600000.00',
            },
            {
                'title': 'Ashoka University Scholarship',
                'provider': 'Ashoka University',
                'amount': '2000000.00',
                'deadline': datetime.now() + timedelta(days=430),
                'description': 'Need-based financial aid for students at Ashoka University.',
                'eligibility': 'Admitted to Ashoka University, demonstrated financial need.',
                'application_process': 'Application during admission process.',
                'website': 'https://www.ashoka.edu.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '7.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'OP Jindal Engineering & Management Scholarship',
                'provider': 'OP Jindal Global University',
                'amount': '500000.00',
                'deadline': datetime.now() + timedelta(days=440),
                'description': 'Merit scholarship for engineering and management students.',
                'eligibility': 'Min 90% in Class XII, admitted to JGU.',
                'application_process': 'Application through university portal.',
                'website': 'https://jgu.edu.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '9.00',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Engineering", "Management"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'Shiv Nadar University Scholarship',
                'provider': 'Shiv Nadar University',
                'amount': '1000000.00',
                'deadline': datetime.now() + timedelta(days=450),
                'description': 'Merit-cum-means scholarship for students at Shiv Nadar University.',
                'eligibility': 'Min 85% in Class XII, family income < Rs. 8 Lakh/annum.',
                'application_process': 'Application during admission process.',
                'website': 'https://snu.edu.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '8.50',
                'max_age': 22,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '800000.00',
            },
            {
                'title': 'Azim Premji University Scholarship',
                'provider': 'Azim Premji University',
                'amount': '500000.00',
                'deadline': datetime.now() + timedelta(days=460),
                'description': 'Need-based financial aid for students at Azim Premji University.',
                'eligibility': 'Admitted to APU, demonstrated financial need.',
                'application_process': 'Application during admission process.',
                'website': 'https://azimpremjiuniversity.edu.in/',
                'scholarship_type': 'need',
                'education_level': 'graduate',
                'min_cgpa': '6.50',
                'max_age': 35,
                'min_age': 21,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'TISS Scholarship for SC/ST',
                'provider': 'Tata Institute of Social Sciences',
                'amount': '100000.00',
                'deadline': datetime.now() + timedelta(days=470),
                'description': 'Scholarship for SC/ST students at TISS.',
                'eligibility': 'SC/ST candidate, enrolled in TISS, min 55% in previous exam.',
                'application_process': 'Application through institute’s SC/ST cell.',
                'website': 'https://www.tiss.edu/',
                'scholarship_type': 'minority',
                'education_level': 'graduate',
                'min_cgpa': '5.50',
                'max_age': 35,
                'min_age': 21,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '[]',
                'minority_preferences': '["Scheduled Caste", "Scheduled Tribe"]',
                'disability_preferences': '[]',
            },
            {
                'title': 'ISI Kolkata Scholarship',
                'provider': 'Indian Statistical Institute',
                'amount': '120000.00',
                'deadline': datetime.now() + timedelta(days=480),
                'description': 'Merit scholarship for students at ISI Kolkata.',
                'eligibility': 'Enrolled in ISI Kolkata, min 8.0 CGPA in previous semester.',
                'application_process': 'Automatic consideration based on academic performance.',
                'website': 'https://www.isical.ac.in/',
                'scholarship_type': 'merit',
                'education_level': 'graduate',
                'min_cgpa': '8.00',
                'max_age': 30,
                'min_age': 21,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Statistics", "Mathematics", "Computer Science"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'NLSIU Bangalore Scholarship',
                'provider': 'National Law School of India University',
                'amount': '200000.00',
                'deadline': datetime.now() + timedelta(days=490),
                'description': 'Need-based scholarship for law students at NLSIU.',
                'eligibility': 'Enrolled in NLSIU, demonstrated financial need.',
                'application_process': 'Application through university financial aid office.',
                'website': 'https://www.nls.ac.in/',
                'scholarship_type': 'need',
                'education_level': 'undergraduate',
                'min_cgpa': '6.50',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Law"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
            },
            {
                'title': 'NLU Delhi Scholarship',
                'provider': 'National Law University Delhi',
                'amount': '150000.00',
                'deadline': datetime.now() + timedelta(days=500),
                'description': 'Merit-cum-means scholarship for students at NLU Delhi.',
                'eligibility': 'Min 75% in previous exam, family income < Rs. 5 Lakh/annum.',
                'application_process': 'Application through university scholarship cell.',
                'website': 'https://nludelhi.ac.in/',
                'scholarship_type': 'merit',
                'education_level': 'undergraduate',
                'min_cgpa': '7.50',
                'max_age': 25,
                'min_age': 17,
                'citizenship_requirements': '["India"]',
                'field_of_study_requirements': '["Law"]',
                'minority_preferences': '[]',
                'disability_preferences': '[]',
                'income_max': '500000.00',
            },
        ]

        for data in scholarships:
            # Handle optional fields gracefully
            defaults = {k: v for k, v in data.items() if k not in ['income_max', 'income_min']}
            if 'income_max' in data:
                defaults['income_max'] = data['income_max']
            if 'income_min' in data:
                defaults['income_min'] = data['income_min']

            scholarship, created = Scholarship.objects.update_or_create(
                title=data['title'],
                defaults=defaults
            )

            if created:
                self.stdout.write(self.style.SUCCESS(f'Created scholarship: {data["title"]}'))
            else:
                self.stdout.write(self.style.SUCCESS(f'Updated scholarship: {data["title"]}'))

        self.stdout.write(self.style.SUCCESS('Successfully loaded 50+ real Indian scholarship samples!'))